### ISSUE TITLE
Ajout d'un bouton pour poster directement depuis une page de hobbie

### ISSUE THREAD

**Issue by ThomasEscorne** [lipingZLP/my-hobbies#1]
Ajouter un bouton dans les pages de hobbie qui permettra à l'utilisateur de poster directement depuis la page à la place de devoir retourner dans son espace personnel.

**Comment by lipingZLP** [comment]
Bonne idée, je vais faire ça, tu pourras tester demain.

**Comment by lipingZLP** [comment]
C'est en ligne, tu pourras tester quand tu veux.
