### ISSUE TITLE
Remplacer le sélecteur de Hobbie

### ISSUE THREAD

**Issue by ThomasEscorne** [lipingZLP/my-hobbies#2]
Dans la page de création de post, on choisit le type de Hobbie avec un chiffre, il serait plus pertinent d'avoir la liste des noms des hobbies disponnibles dans lesquels on peut poster

**Comment by lipingZLP** [comment]
J'y pensais aussi, je le fais maintenant. Tu pourras essayer demain.

**Comment by lipingZLP** [comment]
C'est en ligne, tu pourras tester quand tu veux.
