### ISSUE TITLE
Page home

### ISSUE THREAD

**Issue by ThomasEscorne** [lipingZLP/my-hobbies#3]
La page home est très vide.
Il pourrait être intéressant de la remplir avec des post de tous les hobbies, triés par date de publication par exemple.

**Comment by lipingZLP** [comment]
Bonjour Thomas,

Je suis en train de travailler sur ce point, je te répond dès que j'ai trouvé une solution d'ici ce soir

**Comment by lipingZLP** [comment]
Tu as raison la page est très vide. J'ai modifié tout le design et fait en sorte que quand on se connecte la première fois (et que l'on n'a pas de followers, donc rien a l'écran) un composant de bienvenue est affiché et il explique à l'utilisateur comment avoir des posts ce qui rend la page un peu moins vide :

![Screenshot_2020-08-20 My Hobbies](https://user-images.githubusercontent.com/65895402/90803025-6b787c80-e318-11ea-9038-51b0c6c57ce6.png)

La home de l'utilisateur doit être personalisée et montrer les posts des gens qu'il follow pour créer des liens (et pas des inconnus).
Si l'utilisateur souhaite consulter les posts des personnes qu'il ne connait pas, il peut aller dans les différentes catégories en haut qui montrent justement ce que tu souhaites c'est à dire les posts des personnes qu'il ne connait pas triés par date de publication.

En ce qui concerne la toute première page du site (non connecté), j'ai modifié tout le design pour que ça soit plus joli mais je ne souhaite pas afficher des posts ici pour inciter les utilisateurs à créer un compte afin de voir du contenu.
